package Hibernate.moma.com;
// Generated 2013-5-12 3:09:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userRealName;
     private String userPassword;
     private String userEmail;
     private Set<User> usersForFirstUserId = new HashSet<User>(0);
     private Set<User> usersForSecondUserId = new HashSet<User>(0);
     private Set<Diary> diaries = new HashSet<Diary>(0);
     private Set<Brochure> brochures = new HashSet<Brochure>(0);
     private Set<Video> videos = new HashSet<Video>(0);
     private Set<Photo> photos = new HashSet<Photo>(0);
     private Set<Blessing> blessings = new HashSet<Blessing>(0);

    public User() {
    }

	
    public User(String userName, String userRealName, String userPassword, String userEmail) {
        this.userName = userName;
        this.userRealName = userRealName;
        this.userPassword = userPassword;
        this.userEmail = userEmail;
    }
    public User(String userName, String userRealName, String userPassword, String userEmail, Set<User> usersForFirstUserId, Set<User> usersForSecondUserId, Set<Diary> diaries, Set<Brochure> brochures, Set<Video> videos, Set<Photo> photos, Set<Blessing> blessings) {
       this.userName = userName;
       this.userRealName = userRealName;
       this.userPassword = userPassword;
       this.userEmail = userEmail;
       this.usersForFirstUserId = usersForFirstUserId;
       this.usersForSecondUserId = usersForSecondUserId;
       this.diaries = diaries;
       this.brochures = brochures;
       this.videos = videos;
       this.photos = photos;
       this.blessings = blessings;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserRealName() {
        return this.userRealName;
    }
    
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Set<User> getUsersForFirstUserId() {
        return this.usersForFirstUserId;
    }
    
    public void setUsersForFirstUserId(Set<User> usersForFirstUserId) {
        this.usersForFirstUserId = usersForFirstUserId;
    }
    public Set<User> getUsersForSecondUserId() {
        return this.usersForSecondUserId;
    }
    
    public void setUsersForSecondUserId(Set<User> usersForSecondUserId) {
        this.usersForSecondUserId = usersForSecondUserId;
    }
    public Set<Diary> getDiaries() {
        return this.diaries;
    }
    
    public void setDiaries(Set<Diary> diaries) {
        this.diaries = diaries;
    }
    public Set<Brochure> getBrochures() {
        return this.brochures;
    }
    
    public void setBrochures(Set<Brochure> brochures) {
        this.brochures = brochures;
    }
    public Set<Video> getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set<Video> videos) {
        this.videos = videos;
    }
    public Set<Photo> getPhotos() {
        return this.photos;
    }
    
    public void setPhotos(Set<Photo> photos) {
        this.photos = photos;
    }
    public Set<Blessing> getBlessings() {
        return this.blessings;
    }
    
    public void setBlessings(Set<Blessing> blessings) {
        this.blessings = blessings;
    }




}


