package com.entity.moma;
// Generated 2013-6-16 3:35:49 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Brochure generated by hbm2java
 */
public class Brochure  implements java.io.Serializable {


     private Integer brochureId;
     private String brochureName;
     private Date brochureStartTime;
     private int brochureType;
     private int brochureRoot;
     private String brochureDescription;
     private String brochureImageUrl;
     private String latestChange;
     private String latestChangeType;
     private Integer brochureVisit;
     private Set<Diary> diaries = new HashSet<Diary>(0);
     private Set<Blessing> blessings = new HashSet<Blessing>(0);
     private Set<Video> videos = new HashSet<Video>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<Photo> photos = new HashSet<Photo>(0);
     private Set<User> users_1 = new HashSet<User>(0);

    public Brochure() {
    }

	
    public Brochure(String brochureName, Date brochureStartTime, int brochureType, int brochureRoot) {
        this.brochureName = brochureName;
        this.brochureStartTime = brochureStartTime;
        this.brochureType = brochureType;
        this.brochureRoot = brochureRoot;
    }
    public Brochure(String brochureName, Date brochureStartTime, int brochureType, int brochureRoot, String brochureDescription, String brochureImageUrl, String latestChange, String latestChangeType, Integer brochureVisit, Set<Diary> diaries, Set<Blessing> blessings, Set<Video> videos, Set<User> users, Set<Photo> photos, Set<User> users_1) {
       this.brochureName = brochureName;
       this.brochureStartTime = brochureStartTime;
       this.brochureType = brochureType;
       this.brochureRoot = brochureRoot;
       this.brochureDescription = brochureDescription;
       this.brochureImageUrl = brochureImageUrl;
       this.latestChange = latestChange;
       this.latestChangeType = latestChangeType;
       this.brochureVisit = brochureVisit;
       this.diaries = diaries;
       this.blessings = blessings;
       this.videos = videos;
       this.users = users;
       this.photos = photos;
       this.users_1 = users_1;
    }
   
    public Integer getBrochureId() {
        return this.brochureId;
    }
    
    public void setBrochureId(Integer brochureId) {
        this.brochureId = brochureId;
    }
    public String getBrochureName() {
        return this.brochureName;
    }
    
    public void setBrochureName(String brochureName) {
        this.brochureName = brochureName;
    }
    public Date getBrochureStartTime() {
        return this.brochureStartTime;
    }
    
    public void setBrochureStartTime(Date brochureStartTime) {
        this.brochureStartTime = brochureStartTime;
    }
    public int getBrochureType() {
        return this.brochureType;
    }
    
    public void setBrochureType(int brochureType) {
        this.brochureType = brochureType;
    }
    public int getBrochureRoot() {
        return this.brochureRoot;
    }
    
    public void setBrochureRoot(int brochureRoot) {
        this.brochureRoot = brochureRoot;
    }
    public String getBrochureDescription() {
        return this.brochureDescription;
    }
    
    public void setBrochureDescription(String brochureDescription) {
        this.brochureDescription = brochureDescription;
    }
    public String getBrochureImageUrl() {
        return this.brochureImageUrl;
    }
    
    public void setBrochureImageUrl(String brochureImageUrl) {
        this.brochureImageUrl = brochureImageUrl;
    }
    public String getLatestChange() {
        return this.latestChange;
    }
    
    public void setLatestChange(String latestChange) {
        this.latestChange = latestChange;
    }
    public String getLatestChangeType() {
        return this.latestChangeType;
    }
    
    public void setLatestChangeType(String latestChangeType) {
        this.latestChangeType = latestChangeType;
    }
    public Integer getBrochureVisit() {
        return this.brochureVisit;
    }
    
    public void setBrochureVisit(Integer brochureVisit) {
        this.brochureVisit = brochureVisit;
    }
    public Set<Diary> getDiaries() {
        return this.diaries;
    }
    
    public void setDiaries(Set<Diary> diaries) {
        this.diaries = diaries;
    }
    public Set<Blessing> getBlessings() {
        return this.blessings;
    }
    
    public void setBlessings(Set<Blessing> blessings) {
        this.blessings = blessings;
    }
    public Set<Video> getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set<Video> videos) {
        this.videos = videos;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<Photo> getPhotos() {
        return this.photos;
    }
    
    public void setPhotos(Set<Photo> photos) {
        this.photos = photos;
    }
    public Set<User> getUsers_1() {
        return this.users_1;
    }
    
    public void setUsers_1(Set<User> users_1) {
        this.users_1 = users_1;
    }




}


