package com.entity.moma;
// Generated 2013-6-16 12:29:23 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Video generated by hbm2java
 */
public class Video  implements java.io.Serializable {


     private Integer videoId;
     private Brochure brochure;
     private User user;
     private Date videoStartTime;
     private String videoUrl;
     private String videoTitle;
     private Date videoModifyTime;

    public Video() {
    }

	
    public Video(Brochure brochure, User user, Date videoStartTime, String videoUrl, String videoTitle) {
        this.brochure = brochure;
        this.user = user;
        this.videoStartTime = videoStartTime;
        this.videoUrl = videoUrl;
        this.videoTitle = videoTitle;
    }
    public Video(Brochure brochure, User user, Date videoStartTime, String videoUrl, String videoTitle, Date videoModifyTime) {
       this.brochure = brochure;
       this.user = user;
       this.videoStartTime = videoStartTime;
       this.videoUrl = videoUrl;
       this.videoTitle = videoTitle;
       this.videoModifyTime = videoModifyTime;
    }
   
    public Integer getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }
    public Brochure getBrochure() {
        return this.brochure;
    }
    
    public void setBrochure(Brochure brochure) {
        this.brochure = brochure;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getVideoStartTime() {
        return this.videoStartTime;
    }
    
    public void setVideoStartTime(Date videoStartTime) {
        this.videoStartTime = videoStartTime;
    }
    public String getVideoUrl() {
        return this.videoUrl;
    }
    
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }
    public String getVideoTitle() {
        return this.videoTitle;
    }
    
    public void setVideoTitle(String videoTitle) {
        this.videoTitle = videoTitle;
    }
    public Date getVideoModifyTime() {
        return this.videoModifyTime;
    }
    
    public void setVideoModifyTime(Date videoModifyTime) {
        this.videoModifyTime = videoModifyTime;
    }




}


